---
title: "Toehold Switches"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(Biostrings)
library(tidyr)
library(dplyr)
library(seqinr)
library(LncFinder)
#setwd("/Users/wisserlab1/Library/Mobile Documents/com~apple~CloudDocs/Desktop/ToeholdSwitch_project")
MCMV_seq<- read.csv("MCMV_new.csv", header = TRUE)
SCMV_seq <- read.csv("SCMV_seq.csv", header = TRUE)
```


```{r}
#create an empty data frame for the MCMV results
MCMV_res <- data.frame(res=as.character()) 
MCMV_res$res <- as.character(MCMV_res$res)
MCMV_res$id <- as.numeric(MCMV_res$id) 
```


```{r}
#Extract 36-mers from the MCMV sequences

for (i in 1:dim(MCMV_seq)[1]){ #assigning the function to all the rows in the dataframe

	x <- MCMV_seq[i,2]
	
lim <- MCMV_seq[i,3]-35 #defining the left limit
	
  MCMV_res2 <- data.frame(res=as.character()) #create another data frame for the results with more than 36nt
  MCMV_res2$res <- as.character(MCMV_res2$res)
  MCMV_res2$id <- as.numeric(MCMV_res2$id)

if (lim == 1){
  
  MCMV_res3 <- data.frame(res=as.character()) #create a data frame for the results with 36nt
  MCMV_res3$res <- as.character(MCMV_res3$res)
  MCMV_res3$id <- as.numeric(MCMV_res3$id)
	MCMV_res3[1, 1] <-as.character(x)
	MCMV_res3[1, 2] <- i
  
MCMV_res <- rbind(MCMV_res, MCMV_res3)
  
} else{

  
	for (j in 1:lim){
		IN <- j			
		END <- j + 35 #defining the right limit
		s <- substr(x, IN, END)
		

		MCMV_res2[j, 1] <-s
		MCMV_res2[j, 2] <- i
	}
MCMV_res <- rbind(MCMV_res, MCMV_res2)
 }
}

```

```{r}
#converting res column into DNAStringset
MCMV_res$res <- DNAStringSet(MCMV_res$res) 
#get the reverse complement DNA bases for the toehold domain
MCMV_res$rev_complement <- reverseComplement(MCMV_res$res)
#reorder the columns
MCMV_res <- MCMV_res [,c("id","res","rev_complement")] 
```

```{r}
#Import LacZ_gene file as DNAString
LacZ_gene <- readDNAStringSet("sequence.fasta")
```

```{r}
#split toehold sequence into a & b domains using Biostrings package
MCMV_res$domain_a <- subseq(MCMV_res$rev_complement,start = 1, end = 25, width = NA)
width(MCMV_res$domain_a) #width should be 25
MCMV_res$domain_b <- subseq(MCMV_res$rev_complement,start = 26, end = 36, width = NA)
width(MCMV_res$domain_b) #width should be 11
```

```{r}
#extract the first 25 bases in LacZ_gene
x1 <- as.character(subseq(LacZ_gene,start = 1, end = 25, width = NA)) #store as an XString object
#reverse complement of domain a
MCMV_res$revcom_a <- reverseComplement(MCMV_res$domain_a)
#matching LacZ gene to reverse complement of domain a
LacZ_mcmv <- vmatchPattern(x1, MCMV_res$revcom_a)
LacZ_mcmv <- data.frame(vcountPattern(x1, MCMV_res$revcom_a)) #results for the matches
#no sequences are complementary to the LacZ sequence
```

```{r}
#get reverse complement of domain b
MCMV_res$revcom_b <- reverseComplement(MCMV_res$domain_b)
#finding matches stop codons,"TAG","TAA","TGA" in revcom_b sequences 
m1 <- data.frame(vmatchPattern("TAG",MCMV_res$revcom_b))
m2 <- data.frame(vmatchPattern("TAA",MCMV_res$revcom_b))
m3 <- data.frame(vmatchPattern("TGA",MCMV_res$revcom_b))
```


```{r}
#naming the first unnamed column
MCMV_res<-data.frame("X" = rownames(MCMV_res),MCMV_res, row.names = NULL)
#filter out sequences with stop codons
MCMV <- MCMV_res[!(MCMV_res$X) %in% c(m1$group, m2$group, m3$group),]
#renumbering row names
row.names(MCMV) <- 1:nrow(MCMV)
#reordering the first column
MCMV$X = 1:nrow(MCMV) 
```

```{r}
#creating a column for the conserved region
MCMV$conserved <- rep("GGACTTTAGAACAGAGGAGATAAAGATG", length(MCMV$X))
MCMV <- MCMV[,c("X","id","res","rev_complement","domain_a","domain_b","conserved","revcom_a","revcom_b")] #reorder the columns
MCMV$conserved <- DNAStringSet(MCMV$conserved)
#joining the switch sequence
MCMV$switch <- paste0(MCMV$domain_a, MCMV$domain_b,MCMV$conserved, MCMV$revcom_b, sep = "") 
```

```{r}
write.csv(MCMV, file ="MCMV_toeholds.csv") 
#analyze the interaction of the switch and the trigger using NUPACK
MCMV_complex_str <- MCMV[MCMV$X %in% c(7:9,22,44:46,48,50,55,58,61,63,66:69,71:73,76,80,88:95,97:101,103:105,107,110,143,148,149,151,159:161,164,176,185:187,191,194,196:200,210,229,230,240,243:246,254,275,277,280),]
write.csv(MCMV_complex_str, file ="MCMV_2_toeholds.csv") 
#analyze the switch sequence secondary structure using NUPACK

```

```{r}
#Checking the secondary structure of the sequences using RNAfold to compare results with NUPACK results
MCMV_switch <- setNames(MCMV_complex_str$switch, MCMV_complex_str$X)
chartr("T", "U", MCMV_switch) #converting the toehold sequence from DNA to RNA
MCMV_SS <- run_RNAfold(MCMV_switch, RNAfold.path = "RNAfold", parallel.cores = -1)
MCMV_SS <- as.data.frame(t(MCMV_SS)) #transposing the dataframe
match_pattern <- as.character(".........................(((((((((((.(.(((((............))))).).)))))))))))")
MCMV_SS_match <- subset(MCMV_SS, MCMV_SS$V2 == match_pattern)
#naming the first unnamed column
MCMV_SS_match <- data.frame("ID"= rownames(MCMV_SS_match), MCMV_SS_match, row.names = NULL)
#dropping X
MCMV_SS_match$ID <-(substring(MCMV_SS_match$ID, 2))
#adding the trigger sequences from MCVM dataframe
MCMV_SS_match$Trigger <- MCMV$res[MCMV$X %in% MCMV_SS_match$ID]
#naming the first unamed column
MCMV_SS_match <- data.frame("No"= rownames(MCMV_SS_match), MCMV_SS_match, row.names = NULL)
```
 
```{r}
linker_seq <- "AACCTGGCGGCAGCGCAAAAG" #21nts linker sequence
MCMV_SS_match$toehold_switch <- paste0(MCMV_SS_match$V1, linker_seq, sep = "")
```
 
```{r}
#synthetic sequences to be ordered from vendor 
#21 nts linker sequence and the first 9 LacZ nts
Linker_LacZ <- "AACCTGGCGGCAGCGCAAAAGATGACCATG"
T7_promoter <- "TAATACGACTCACTATAGGG"
T7_terminator <- "TAGCATAACCCCTTGGGGCCTCTAAACGGG"

chartr("U", "T", MCMV_SS_match$V1)
MCMV_SS_match$Synthetic_switch <- paste0(T7_promoter,MCMV_SS_match$V1,Linker_LacZ,sep = "")
MCMV_SS_match$Synthetic_trigger <- paste0(T7_promoter,MCMV_SS_match$Trigger,T7_terminator,sep = "")
```

```{r}
write.csv(MCMV_SS_match, file ="MCMV_Sensors.csv")
```

```{r}
#SCMV
#create an empty data frame for the SCMV results
SCMV_res <- data.frame(res=as.character())
SCMV_res$res <- as.character(SCMV_res$res) 
SCMV_res$id <- as.numeric(SCMV_res$id) 
```

```{r}
#Extract 36-mers from the MCMV sequences

for (i in 1:dim(SCMV_seq)[1]){ #assigning the function to all the rows in the dataframe

	x <- SCMV_seq[i,2]
	
lim <- SCMV_seq[i,3]-35 #defining the left limit
	
  SCMV_res2 <- data.frame(res=as.character()) #create another data frame for the results with more than 36nt
  SCMV_res2$res <- as.character(SCMV_res2$res)
  SCMV_res2$id <- as.numeric(SCMV_res2$id)

if (lim == 1){
  
  SCMV_res3 <- data.frame(res=as.character()) #create a data frame for the results with 36nt
  SCMV_res3$res <- as.character(SCMV_res3$res)
  SCMV_res3$id <- as.numeric(SCMV_res3$id)
	SCMV_res3[1, 1] <-as.character(x)
	SCMV_res3[1, 2] <- i
  
SCMV_res <- rbind(SCMV_res, SCMV_res3)
  
} else{

  
	for (j in 1:lim){
		IN <- j			
		END <- j + 35 #defining the right limit
		s <- substr(x, IN, END)
		

		SCMV_res2[j, 1] <-s
		SCMV_res2[j, 2] <- i
	}
SCMV_res <- rbind(SCMV_res, SCMV_res2)
 }
}


```

```{r}
#convert res column into DNAStringset
SCMV_res$res <- DNAStringSet(SCMV_res$res) 
#get the reverse complement DNA bases for the toehold domain
SCMV_res$rev_complement <- reverseComplement(SCMV_res$res) 
SCMV_res <- SCMV_res[,c("id","res","rev_complement")] #reorder the columns
```

```{r}
#split toehold sequence into a & b domains using Biostrings package
SCMV_res$domain_a <- subseq(SCMV_res$rev_complement,start = 1, end = 25, width = NA)
width(SCMV_res$domain_a) #width should be 25
SCMV_res$domain_b <- subseq(SCMV_res$rev_complement,start = 26, end = 36, width = NA)
width(SCMV_res$domain_b) #width should be 11
```


```{r}
#get the reverse complement of domain a 
SCMV_res$revcom_a <- reverseComplement(SCMV_res$domain_a)
#match LacZ gene to reverse complement of domain a
LacZ_scmv <- vmatchPattern(x1, SCMV_res$revcom_a)
LacZ_scmv <- data.frame(vcountPattern(x1, SCMV_res$revcom_a)) #results for the matches. No sequences are complementary to LacZ sequence
```

```{r}
#get the reverse complement of domain b
SCMV_res$revcom_b <- reverseComplement(SCMV_res$domain_b)
#find matches for stop codons,"TAG","TAA","TGA" in revcom_b sequences 
match1 <- data.frame(vmatchPattern("TAG",SCMV_res$revcom_b))
match2 <- data.frame(vmatchPattern("TAA",SCMV_res$revcom_b))
match3 <- data.frame(vmatchPattern("TGA",SCMV_res$revcom_b))
```

```{r}
#naming the first unnamed column
SCMV_res<-data.frame("X" = rownames(SCMV_res),SCMV_res, row.names = NULL)
#remove rows with stop codons
SCMV <- SCMV_res[!(SCMV_res$X) %in% c(match1$group, match2$group, match3$group),]
#reorder the row names
rownames(SCMV) <- 1:nrow(SCMV) 
#reorder the first column
SCMV$X = 1:nrow(SCMV) 
```

```{r}
#create a column for the conserved sequence with the same sequence
SCMV$conserved <- rep("GGACTTTAGAACAGAGGAGATAAAGATG", length(SCMV$X))
SCMV <- SCMV [,c("X","id","res","rev_complement","domain_a","domain_b","conserved","revcom_a","revcom_b")] #reorder the columns
SCMV$conserved <- DNAStringSet(SCMV$conserved)
#join the switch sequence
SCMV$switch <- paste0(SCMV$domain_a, SCMV$domain_b,SCMV$conserved, SCMV$revcom_b, sep = "") 
```

```{r}
write.csv(SCMV, file ="SCMV_toeholds.csv") 
#analyze the interaction of the switch and the trigger using NUPACK
SCMV_complex_str <- SCMV[SCMV$X %in% c(4:6,18,28:31,33,73,80,81,89,99,101,102,117,137,142,144,147:150,152,153,159),]
write.csv(SCMV_complex_str, file ="SCMV_2_toeholds.csv") 
#analyze the switch sequence secondary structure using NUPACK
```


```{r}
#Checking the secondary structure of the sequences using RNAfold to compare results with NUPACK results
SCMV_switch <- setNames(SCMV_complex_str$switch, SCMV_complex_str$X)
chartr("T", "U", SCMV_switch) #converting the toehold sequence from DNA to RNA
SCMV_SS <- run_RNAfold(SCMV_switch, RNAfold.path = "RNAfold", parallel.cores = -1)
SCMV_SS <- as.data.frame(t(SCMV_SS))
SCMV_SS_match <- subset(SCMV_SS, SCMV_SS$V2 == match_pattern)
#naming the first unnamed column
SCMV_SS_match <- data.frame("ID"= rownames(SCMV_SS_match), SCMV_SS_match, row.names = NULL)
#dropping X
SCMV_SS_match$ID <- (substring(SCMV_SS_match$ID, 2))

#adding the trigger sequences from SCVM dataframe
SCMV_SS_match$Trigger <- SCMV$res[SCMV$X %in% SCMV_SS_match$ID]
#naming the first unamed column
SCMV_SS_match <- data.frame("No"= rownames(SCMV_SS_match), SCMV_SS_match, row.names = NULL)
```

```{r}
SCMV_SS_match$toehold_switch <- paste0(SCMV_SS_match$V1, linker_seq, sep = "")
```

```{r}
#synthetic sequences to be ordered from vendor 
#21 nts linker sequence and the first 9 LacZ nts
chartr("U", "T", SCMV_SS_match$V1)
SCMV_SS_match$Synthetic_switch <- paste0(T7_promoter,SCMV_SS_match$V1,Linker_LacZ,sep = "")
SCMV_SS_match$Synthetic_trigger <- paste0(T7_promoter,SCMV_SS_match$Trigger,T7_terminator,sep = "")

```

```{r}
write.csv(SCMV_SS_match, file ="SCMV_Sensors.csv")
```
 

```{r}
B_gal_MLN <- read.csv("MLN-B-gal.csv", header = TRUE)
T <- 10 #reaction time in minutes
V <- 0.1 #volume of the cell lysate in milliliters

B_gal_MLN$Miller_units <- 1000*((B_gal_MLN$Average-(1.75*B_gal_MLN$Average.1))/(T*V*B_gal_MLN$A600))

ggplot(B_gal_MLN,aes(fill= Samples, y= Miller_units, x=Samples)) + geom_bar(position = "dodge", stat ="identity")

```


```{r}
MLN_data_summary <- plyr::ddply (B_gal_MLN, "Samples" , plyr::summarise, mean = mean (Miller_units), median = median(Miller_units), var = var (Miller_units), sd = sd (Miller_units), se = sd(Miller_units)/sqrt(3))

#t-tests
#Ho = the mean difference between group a and group b is equal to zero
#Ha = the mean difference between group a and group b is not equal to zero
t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_1a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_1b"] )

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_2a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_2b"] )

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_3a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_3b"] )

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_4a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_4b"] )

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_5a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_5b"] )

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_1a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_1b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_2a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_2b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_3a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_3b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_4a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_4b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_5a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_5b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_6a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_6b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_1a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_1b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_1a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_1b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_2a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_2b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_3a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_3b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_4a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_4b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_5a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="MC_TS_5b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_1a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_1b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_2a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_2b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_3a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_3b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_4a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_4b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_5a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_5b"])

t.test(B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_6a"], B_gal_MLN$Miller_units[B_gal_MLN$Samples=="SC_TS_6b"])

#New dataframe to store the p-values
MLN_test_results <- data.frame(group_a = as.character(c("MC_1a","MC_2a","MC_3a","MC_4a","MC_5a","MC_TS_1a","MC_TS_2a","MC_TS_3a","MC_TS_4a","MC_TS_5a","SC_1a","SC_2a","SC_3a","SC_4a","SC_5a","SC_6a","SC_TS_1a","SC_TS_2a","SC_TS_3a","SC_TS_4a","SC_TS_5a","SC_TS_6a")))

MLN_test_results$group_b <- as.character(c("MC_1b","MC_2b","MC_3b","MC_4b","MC_5b","MC_TS_1b","MC_TS_2b","MC_TS_3b","MC_TS_4b","MC_TS_5b","SC_1b","SC_2b","SC_3b","SC_4b","SC_5b","SC_6b","SC_TS_1b","SC_TS_2b","SC_TS_3b","SC_TS_4b","SC_TS_5b","SC_TS_6b"))

# The p-values are rounded off to four decimal places

MLN_test_results$p_value <- as.numeric(c("0.1939","0.5046","0.2108","0.0007","0.0481","0.6286","0.6373","0.3142","0.0042","0.0010","0.1421","0.2491","0.0000","0.1735","0.0141","0.8001","0.1661","0.0033","0.3185","0.0107","0.0005","0.7206"))

```

```{r}
#Adding the mean values of each sample into the MLN_test_results data frame
MLN_test_results$group_a_mean <- subset(MLN_data_summary$mean, MLN_data_summary$Samples %in% MLN_test_results$group_a)
MLN_test_results$group_b_mean <- subset(MLN_data_summary$mean, MLN_data_summary$Samples %in% MLN_test_results$group_b)

#Get the mean difference of the two groups (independent replicates)
MLN_test_results$means_difference <- MLN_test_results$group_a_mean - MLN_test_results$group_b_mean

#add the standard deviation of each sample
MLN_test_results$SD_a <- subset(MLN_data_summary$sd, MLN_data_summary$Samples %in% MLN_test_results$group_a)
MLN_test_results$SD_b <- subset(MLN_data_summary$sd, MLN_data_summary$Samples %in% MLN_test_results$group_b)

#calculate pooled standard deviation
MLN_test_results$pooled_SD <- sqrt((MLN_test_results$SD_a^2 + MLN_test_results$SD_b^2) / 2)

#calculate the power 
power.t.test(n=3, delta = MLN_test_results$means_difference, sd = MLN_test_results$pooled_SD, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "two.sided")

#add the power values into the data frame
MLN_test_results$power <- c(0.31534450, 0.08700739, 0.28241125, 0.99999852, 0.63419103, 0.18334442, 1.00000000, 0.32756604, 0.99994695, 0.04167624, 0.06347810, 0.05973298, 0.14400156, 1.00000000, 1.00000000, 0.28976643, 0.28359166, 1.00000000, 0.16767708, 0.99999319, 1.00000000, 0.04982239)

```

```{r}
#Putting MC and SC values in separate data frames

MC_Miller_Units <- data.frame(MC_S_a = as.character(B_gal_MLN$Samples[c(1:3,7:9,13:15,19:21,25:27,31:33)]),Miller_Units_S_a = as.numeric(B_gal_MLN$Miller_units[c(1:3,7:9,13:15,19:21,25:27,31:33)]),MC_TS_a = as.character(B_gal_MLN$Samples[c(73:75,79:81,85:87,91:93,97:99,103:105)]), Miller_Units_TS_a = as.numeric(B_gal_MLN$Miller_units[c(73:75,79:81,85:87,91:93,97:99,103:105)]),MC_S_b = as.character(B_gal_MLN$Samples[c(4:6,10:12,16:18,22:24,28:33)]),Miller_Units_S_b = as.numeric(B_gal_MLN$Miller_units[c(4:6,10:12,16:18,22:24,28:33)]),MC_TS_b = as.character(B_gal_MLN$Samples[c(76:78,82:84,88:90,94:96,100:105)]), Miller_Units_TS_b = as.numeric(B_gal_MLN$Miller_units[c(76:78,82:84,88:90,94:96,100:105)]))

SC_Miller_Units <- data.frame(SC_S_a = as.character(B_gal_MLN$Samples[c(37:39,43:45,49:51,55:57,61:63,67:69,34:36)]),Miller_Units_S_a = as.numeric(B_gal_MLN$Miller_units[c(37:39,43:45,49:51,55:57,61:63,67:69,34:36)]),SC_TS_a = as.character(B_gal_MLN$Samples[c(109:111,115:117,121:123,127:129,133:135,139:141,106:108)]), Miller_Units_TS_a = as.numeric(B_gal_MLN$Miller_units[c(109:111,115:117,121:123,127:129,133:135,139:141,106:108)]),SC_S_b = as.character(B_gal_MLN$Samples[c(40:42,46:48,52:54,58:60,64:66,70:72,34:36)]),Miller_Units_S_b = as.numeric(B_gal_MLN$Miller_units[c(40:42,46:48,52:54,58:60,64:66,70:72,34:36)]),SC_TS_b = as.character(B_gal_MLN$Samples[c(112:114,118:120,124:126,130:132,136:138,142:144,106:108)]), Miller_Units_TS_b = as.numeric(B_gal_MLN$Miller_units[c(112:114,118:120,124:126,130:132,136:138,142:144,106:108)]))

#visualizing MC data
ggboxplot(MC_Miller_Units, x = "MC_S_a", y = "Miller_Units_S_a", color = "MC_S_a", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(MC_Miller_Units, x = "MC_TS_a", y = "Miller_Units_TS_a", color = "MC_TS_a", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(MC_Miller_Units, x = "MC_S_b", y = "Miller_Units_S_b", color = "MC_S_b", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(MC_Miller_Units, x = "MC_TS_b", y = "Miller_Units_TS_b", color = "MC_TS_b", palette = NULL, ylab = "Miller Units", xlab = "Samples")

#ANOVA test for MC switches, group a
summary(MC_res1.aov <- aov(Miller_Units_S_a ~ MC_S_a, data =  MC_Miller_Units))
#ANOVA test for MC switches + triggers, group a
summary(MC_res2.aov <- aov(Miller_Units_TS_a ~ MC_TS_a, data =  MC_Miller_Units))
#ANOVA test for MC switches + triggers, group b
summary(MC_res3.aov <- aov(Miller_Units_S_b ~ MC_S_b, data =  MC_Miller_Units))
#ANOVA test for MC switches + triggers, group b
summary(MC_res4.aov <- aov(Miller_Units_TS_b ~ MC_TS_b, data =  MC_Miller_Units))

#multiple comparison of means
TukeyHSD(MC_res1.aov)
TukeyHSD(MC_res2.aov)
TukeyHSD(MC_res3.aov)
TukeyHSD(MC_res4.aov)

#visualizing SC data
ggboxplot(SC_Miller_Units, x = "SC_S_a", y = "Miller_Units_S_a", color = "SC_S_a", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(SC_Miller_Units, x = "SC_TS_a", y = "Miller_Units_TS_a", color = "SC_TS_a", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(SC_Miller_Units, x = "SC_S_b", y = "Miller_Units_S_b", color = "SC_S_b", palette = NULL, ylab = "Miller Units", xlab = "Samples")
ggboxplot(SC_Miller_Units, x = "SC_TS_b", y = "Miller_Units_TS_b", color = "SC_TS_b", palette = NULL, ylab = "Miller Units", xlab = "Samples")

#ANOVA test for SC switches, group a
summary(SC_res1.aov <- aov(Miller_Units_S_a ~ SC_S_a, data =  SC_Miller_Units))
#ANOVA test for SC switches + triggers, group a
summary(SC_res2.aov <- aov(Miller_Units_TS_a ~ SC_TS_a, data =  SC_Miller_Units))
#ANOVA test for SC switches + triggers, group b
summary(SC_res3.aov <- aov(Miller_Units_S_b ~ SC_S_b, data =  SC_Miller_Units))
#ANOVA test for SC switches + triggers, group b
summary(SC_res4.aov <- aov(Miller_Units_TS_b ~ SC_TS_b, data =  SC_Miller_Units))

#multiple comparison of means
TukeyHSD(SC_res1.aov)
TukeyHSD(SC_res2.aov)
TukeyHSD(SC_res3.aov)
TukeyHSD(SC_res4.aov)
```

```{r}
MC_data_summary <- data.frame(MC_S_a = as.character(MLN_data_summary$Samples[c(1,3,5,7,9,11)]), mean_S_a = as.numeric(MLN_data_summary$mean[c(1,3,5,7,9,11)]),sd_S_a = as.numeric(MLN_data_summary$sd[c(1,3,5,7,9,11)]), MC_TS_a = as.character(MLN_data_summary$Samples[c(47,13,15,17,19,21)]), mean_TS_a = as.numeric(MLN_data_summary$mean[c(47,13,15,17,19,21)]), sd_TS_a = as.numeric(MLN_data_summary$sd[c(47,13,15,17,19,21)]), MC_S_b = as.character(MLN_data_summary$Samples[c(1,4,6,8,10,12)]), mean_S_b = as.numeric(MLN_data_summary$mean[c(1,4,6,8,10,12)]), sd_S_b = as.numeric(MLN_data_summary$sd[c(1,4,6,8,10,12)]), MC_TS_b = as.character(MLN_data_summary$Samples[c(47,14,16,18,20,22)]), mean_TS_b = as.numeric(MLN_data_summary$mean[c(47,14,16,18,20,22)]), sd_TS_b = as.numeric(MLN_data_summary$sd[c(47,14,16,18,20,22)]))

SC_data_summary <- data.frame(SC_S_a = as.character(MLN_data_summary$Samples[c(2,23,25,27,29,31,33)]), mean_S_a = as.numeric(MLN_data_summary$mean[c(2,23,25,27,29,31,33)]),sd_S_a = as.numeric(MLN_data_summary$sd[c(2,23,25,27,29,31,33)]), SC_TS_a = as.character(MLN_data_summary$Samples[c(48,35,37,39,41,43,45)]), mean_TS_a = as.numeric(MLN_data_summary$mean[c(48,35,37,39,41,43,45)]), sd_TS_a = as.numeric(MLN_data_summary$sd[c(48,35,37,39,41,43,45)]), SC_S_b = as.character(MLN_data_summary$Samples[c(2,24,26,28,30,32,34)]), mean_S_b = as.numeric(MLN_data_summary$mean[c(2,24,26,28,30,32,34)]), sd_S_b = as.numeric(MLN_data_summary$sd[c(2,24,26,28,30,32,34)]), SC_TS_b = as.character(MLN_data_summary$Samples[c(48,36,38,40,42,44,46)]), mean_TS_b = as.numeric(MLN_data_summary$mean[c(48,36,38,40,42,44,46)]), sd_TS_b = as.numeric(MLN_data_summary$sd[c(48,36,38,40,42,44,46)]))

```


```{r}
#The diffrence between the switches + triggers and the switches i.e. before gene translation and after gene translation
MC_data_summary$mean_diff_a <- MC_data_summary$mean_TS_a - MC_data_summary$mean_S_a
MC_data_summary$mean_diff_b <- MC_data_summary$mean_TS_b - MC_data_summary$mean_S_b

MC_data_summary$pooled_SD_a <- sqrt((MC_data_summary$sd_S_a^2 + MC_data_summary$sd_TS_a^2) / 2)
MC_data_summary$pooled_SD_b <- sqrt((MC_data_summary$sd_S_b^2 + MC_data_summary$sd_TS_b^2) / 2)

SC_data_summary$mean_diff_a <- SC_data_summary$mean_TS_a - SC_data_summary$mean_S_a
SC_data_summary$mean_diff_b <- SC_data_summary$mean_TS_b - SC_data_summary$mean_S_b

SC_data_summary$pooled_SD_a <- sqrt((SC_data_summary$sd_S_a^2 + SC_data_summary$sd_TS_a^2) / 2)
SC_data_summary$pooled_SD_b <- sqrt((SC_data_summary$sd_S_b^2 + SC_data_summary$sd_TS_b^2) / 2)
```

```{r}
MC_data <- data.frame(MLN_data_summary[c(1:22,47:48),])
SC_data <- data.frame(MLN_data_summary[c(1:2,23:48),])

ggplot(MC_data,aes(fill= Samples , y= mean, x= Samples)) + geom_bar(position = "dodge", stat ="identity") + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width=0.2,position=position_dodge(.9))

ggplot(SC_data,aes(fill= Samples , y= mean, x= Samples)) + geom_bar(position = "dodge", stat ="identity") + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width=0.2,position=position_dodge(.9))
```

```{r}
#calculating the standard error of the MC Miller Units mean
sd_MC <- sd(MC_data$mean) 
SE_MC <- sd(MC_data$mean) / sqrt(24) 

#calculating the effect size 
MC_data_summary$d_MC_a <- MC_data_summary$mean_diff_a / MC_data_summary$pooled_SD_a
MC_data_summary$d_MC_b <- MC_data_summary$mean_diff_b / MC_data_summary$pooled_SD_b

power.t.test(n=3, delta = MC_data_summary$mean_diff_a, sd = SE_MC, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "two.sided")

MC_data_summary$power_a <- c(0.46407176, 0.52254135, 0.02770010, 1.00000000, 0.23476949, 0.09198198)

power.t.test(n=3, delta = MC_data_summary$mean_diff_b, sd = SE_MC, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "two.sided")

MC_data_summary$power_b <- c(0.46407176, 0.36195527, 0.03533725, 1.00000000, 1.00000000, 0.10939572)

```


```{r}
#calculating the standard error of the SC Miller Units mean
sd_SC <- sd(SC_data$mean)
SE_SC <- sd(SC_data$mean) / sqrt(24)

#calculating the effect size 
SC_data_summary$d_SC_a <- SC_data_summary$mean_diff_a / SC_data_summary$pooled_SD_a
SC_data_summary$d_SC_b <- SC_data_summary$mean_diff_b / SC_data_summary$pooled_SD_b


power.t.test(n=3, delta = SC_data_summary$mean_diff_a, sd = SE_SC, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "two.sided")

SC_data_summary$power_a <- c(0.42602718, 0.99999509, 0.07299947, 1.00000000, 0.03277375, 0.99999695, 0.99767474)

power.t.test(n=3, delta = SC_data_summary$mean_diff_b, sd = SE_SC, sig.level = 0.05, power = NULL, type = "two.sample", alternative = "two.sided")

SC_data_summary$power_b <- c(0.4260272, 0.9997855, 0.9999216, 1.0000000, 0.2218934, 0.9508414, 0.9994365)
```


```{r}
P1_MC <- ggplot(data = MC_data_summary, aes(x = MC_data_summary$d_MC_a, y = MC_data_summary$power_a)) + geom_line() + labs(x = "Effect size", y = "Power") + labs(title = "Power vs MC_a Miller Units")

P2_MC <- ggplot(data = MC_data_summary, aes(x = MC_data_summary$d_MC_b, y = MC_data_summary$power_b)) + geom_line() + labs(x = "Effect size", y = "Power") + labs(title = "Power vs MC_b Miller Units")

P1_SC <- ggplot(data = SC_data_summary, aes(x = SC_data_summary$d_SC_a, y = SC_data_summary$power_a)) + geom_line() + labs(x = "Effect size", y = "Power") + labs(title = "Power vs SC_a Miller Units")

P2_SC <- ggplot(data = SC_data_summary, aes(x = SC_data_summary$d_SC_b, y = SC_data_summary$power_b)) + geom_line() + labs(x = "Effect size", y = "Power") + labs(title = "Power vs SC_b Miller Units")
```

```{r}
MLN_sum <- data.frame(group_by(B_gal_MLN, Samples) %>% summarise(count = n(), median = median(Miller_units, na.rm = TRUE), IQR = IQR(Miller_units, na.rm = TRUE)))

ggboxplot(B_gal_MLN, x= "Samples", y = "Miller_units", color = "Samples", ylab = "Miller_units", xlab = "Samples")


pv_MC <- lapply(1:nrow(MC_fold_change), function(i) {(wilcox.test(MC_fold_change$Miller_units_S, MC_fold_change$Miller_units_ST,alt="two.sided", paired = T, conf.int=T,conf.level=0.95, exact=F,correct=F))$p.value})

pvals_MC <- data.frame(matrix(unlist(pv_MC), nrow=length(pv_MC), byrow = T))

pvals_MC$TS <- MC_fold_change$Switch...Trigger
colnames(pvals_MC)[colnames(pvals_MC) == "matrix.unlist.pv_MC...nrow...length.pv_MC...byrow...T."] <- "p_values"
pvals_MC <- pvals_MC[c(2,1)]


```

```{r}
#Extract 36-mers from the MCMV sequences

for (i in 1:dim(SCMV_seq)[1]){ #assigning the function to all the rows in the dataframe

	x <- SCMV_seq[i,2]
	
lim <- SCMV_seq[i,3]-35 #defining the limit
	
  SCMV_res2 <- data.frame(res=as.character()) #create another data frame for the results with more than 36nt
  SCMV_res2$res <- as.character(SCMV_res2$res)
  SCMV_res2$id <- as.numeric(SCMV_res2$id)

if (lim == 1){
  
  SCMV_res3 <- data.frame(res=as.character()) #create a data frame for the results with 36nt
  SCMV_res3$res <- as.character(SCMV_res3$res)
  SCMV_res3$id <- as.numeric(SCMV_res3$id)
	SCMV_res3[1, 1] <-as.character(x)
	SCMV_res3[1, 2] <- i
  
SCMV_res <- rbind(SCMV_res, SCMV_res3)
  
} else{

  
	for (j in 1:lim){
		IN <- j			
		END <- j + 35 #defining the right limit
		s <- substr(x, IN, END)
		

		SCMV_res2[j, 1] <-s
		SCMV_res2[j, 2] <- i
	}
SCMV_res <- rbind(SCMV_res, SCMV_res2)
 }
}

```

